# swagger.yml

openapi: 3.0.0
info:
  title: "Rp flask REST API"
  description: "An API about people and notes"
  version: "1.0.0"

servers:
  - url: "/api"

paths:
  /people:
    get:
      operationId: "people.read_all"
      tags:
        - "People"
      summary: "read the list of people"
      responses:
        "200":
          description: "Successfully red people list"

